# Preprocessing for existing NCF model
>Just involves renaming the columns, no negative sampling even for implicit feedback

>Everything else handled by data.py

### 1. Read CSV

In [1]:
import pandas as pd

In [ ]:
ratings = pd.read_csv('../data/ml-32m/ratings.csv')

In [3]:
ratings.head()

   userId  movieId  rating  timestamp
0       1       17     4.0  944249077
1       1       25     1.0  944250228
2       1       29     2.0  943230976
3       1       30     5.0  944249077
4       1       32     5.0  943228858

### 2. Rename columns

In [4]:
ratings.rename(mapper={'movieId': 'itemId'}, inplace=True, axis=1)

In [5]:
ratings.head()

   userId  itemId  rating  timestamp
0       1      17     4.0  944249077
1       1      25     1.0  944250228
2       1      29     2.0  943230976
3       1      30     5.0  944249077
4       1      32     5.0  943228858

In [ ]:
import os

os.makedirs('../data/ncf_preprocessed', exist_ok=True)
ratings.to_csv('../data/ncf_preprocessed/ratings.csv', index=False)

### 3. Create smaller subsets

In [ ]:
# Create a subset of 1000 users
subset = ratings['userId'].drop_duplicates().sample(n=1000, random_state=42)
subset_ratings = ratings[ratings['userId'].isin(subset)]
subset_ratings.to_csv('../data/ncf_preprocessed/ratings_subset.csv', index=False)

In [ ]:
# Create a subset of 500 users
subset = ratings['userId'].drop_duplicates().sample(n=500, random_state=42)
subset_ratings = ratings[ratings['userId'].isin(subset)]
subset_ratings.to_csv('../data/ncf_preprocessed/ratings_subset_500.csv', index=False)